name: CI

on:
  push:
    branches:
    - development
  pull_request:
    branches:
    - development
    - master

jobs:
  # Build job for building the application
  build:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1

      - name: Build solution
        run: dotnet build
        

    # Test job for testing the application
  test:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: dotnet test
